# Project: PALESDL
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++ #-D__DEBUG__
CC   = gcc #-D__DEBUG__
RES  = 
OBJ  = PALESDL_VID.o PALESDL_IO.o PALESDL.o PALESDL_CONFIG.o PALE48K.o PALEMEM.o PALEROM.o PALE96K.o  PALE_KEYS.o PALETAPS.o PALE128K.o  sge_surface.o sge_rotation.o sge_blib.o sge_primitives.o KOGEL/z80.o KOGEL/KOGELMEM.o KOGEL/KOGELIO.o  PALEDOS_TEMP.o $(RES)
# LINKOBJ  = PALESDL_VID.o PALESDL_IO.o PALESDL.o PALESDL_CONFIG.o PALE48K.o PALEMEM.o PALEROM.o PALE96K.o PALE_KEYS.o PALETAPS.o PALE128K.o  sge_surface.o sge_rotation.o sge_blib.o sge_primitives.o KOGEL/z80.o KOGEL/KOGELMEM.o KOGEL/KOGELIO.o  PALEDOS_TEMP.o $(RES)
LINKOBJ  = PALESDL_IO.o PALESDL.o PALESDL_CONFIG.o PALE48K.o PALEMEM.o PALEROM.o PALE96K.o PALE_KEYS.o PALETAPS.o PALE128K.o  sge_surface.o sge_rotation.o sge_blib.o sge_primitives.o KOGEL/z80.o KOGEL/KOGELMEM.o KOGEL/KOGELIO.o  PALEDOS_TEMP.o $(RES)
LIBS =  
INCS =   
BIN  = PALESDL.exe
CXXFLAGS = $(CXXINCS)   -fexpensive-optimizations -O3 -pg -g3
CFLAGS = $(INCS) -W -fno-exceptions -g -O0  -fexpensive-optimizations -O3 -pg -g3
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before PALESDL.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "PALESDL.exe" $(LIBS) -lSDL

PALESDL_VID.o: PALESDL_VID.C
	$(CPP) -c PALESDL_VID.C -o PALESDL_VID.o $(CXXFLAGS)

PALESDL_IO.o: PALESDL_IO.C
	$(CPP) -c PALESDL_IO.C -o PALESDL_IO.o $(CXXFLAGS)

PALESDL.o: PALESDL.C
	$(CPP) -c PALESDL.C -o PALESDL.o $(CXXFLAGS)

PALESDL_CONFIG.o: PALESDL_CONFIG.C
	$(CPP) -c PALESDL_CONFIG.C -o PALESDL_CONFIG.o $(CXXFLAGS)

PALEMEM.o: PALEMEM.C
	$(CPP) -c PALEMEM.C -o PALEMEM.o $(CXXFLAGS)

PALEROM.o: PALEROM.C
	$(CPP) -c PALEROM.C -o PALEROM.o $(CXXFLAGS)

PALE96K.o: PALE96K.C
	$(CPP) -c PALE96K.C -o PALE96K.o $(CXXFLAGS)

PALE_KEYS.o: PALE_KEYS.C
	$(CPP) -c PALE_KEYS.C -o PALE_KEYS.o $(CXXFLAGS)

PALETAPS.o: PALETAPS.C
	$(CPP) -c PALETAPS.C -o PALETAPS.o $(CXXFLAGS)

KOGEL/z80.o: KOGEL/z80.c
	$(CPP) -c KOGEL/z80.c -o KOGEL/z80.o $(CXXFLAGS)

KOGEL/KOGELMEM.o: KOGEL/KOGELMEM.CPP
	$(CPP) -c KOGEL/KOGELMEM.CPP -o KOGEL/KOGELMEM.o $(CXXFLAGS)

KOGEL/KOGELIO.o: KOGEL/KOGELIO.CPP
	$(CPP) -c KOGEL/KOGELIO.CPP -o KOGEL/KOGELIO.o $(CXXFLAGS)

PALEDOS_TEMP.o: PALEDOS_TEMP.C
	$(CPP) -c PALEDOS_TEMP.C -o PALEDOS_TEMP.o $(CXXFLAGS)
